# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLcUJjFsR4Z3cnJeU4uhSjaq6KE3i5sR
"""

from flask import Flask, request, jsonify
import pandas as pd
from catboost import CatBoostClassifier

MODEL_PATH = "model/catboost_model.cbm"

model = CatBoostClassifier()
model.load_model(MODEL_PATH)

app = Flask(__name__)

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()

    # Load expected feature names from model
    expected_features = model.feature_names_

    # Create full input with defaults
    input_data = {feature: 0.0 for feature in expected_features}

    # Override with provided values
    for key, value in data.items():
        if key in input_data:
            input_data[key] = value

    df = pd.DataFrame([input_data])
    proba = model.predict_proba(df)[0, 1]

    return jsonify({"signal_probability": float(proba)})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9696)