# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLcUJjFsR4Z3cnJeU4uhSjaq6KE3i5sR
"""

from flask import Flask, request, jsonify
import pandas as pd
from catboost import CatBoostClassifier

MODEL_PATH = "model/catboost_model.cbm"

model = CatBoostClassifier()
model.load_model(MODEL_PATH)

app = Flask(__name__)

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    df = pd.DataFrame([data])
    proba = model.predict_proba(df)[0, 1]
    return jsonify({"signal_probability": float(proba)})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9696)