# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NePqWfIHCG9iWPOnSbL3-jWqdtdByKQx
"""

import pandas as pd
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
import os

DATA_PATH = "data/training.csv"
MODEL_PATH = "model/catboost_model.cbm"

def preprocess(df):
    features = [c for c in df.columns if c not in ["EventId", "Label", "Weight"]]

    for col in features:
        median = df.loc[df[col] != -999.0, col].median()
        df[col] = df[col].replace(-999.0, median)

    df["Label"] = df["Label"].map({"s": 1, "b": 0})
    return df, features

def train():
    df = pd.read_csv(DATA_PATH)
    df, features = preprocess(df)

    X = df[features]
    y = df["Label"]

    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    model = CatBoostClassifier(
        iterations=1000,
        learning_rate=0.03,
        depth=8,
        eval_metric="AUC",
        verbose=200,
        random_seed=42
    )

    model.fit(X_train, y_train, eval_set=(X_val, y_val), use_best_model=True)

    os.makedirs("model", exist_ok=True)
    model.save_model(MODEL_PATH)

if __name__ == "__main__":
    train()